### PR TITLE
hypervisor: Code reorganisation

### PR DESCRIPTION
**Pull request by sameo**
Only add hypervisor modules, and keep the hypervisor arch specific bits
inside the hypervisor modules themselves.

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

### CODE REVIEW

**Comment by russell-islam** [comment]
Reorganization seems reasonable to me.

**Comment by russell-islam** [comment]
@sameo Could you please rebase against my branch? I tried to push to your branch but failed due to access permission.

**Comment by sameo** [comment]
@russell-islam I rebased now. What I have in mind though is for cab6ec6 to be merged into 1a8be25444516b6170c192de49604ce3a2a75441. What do you say?

**Comment by russell-islam** [comment]
Sounds good.

**Pull request merged**
